[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hhat-lang"
description = "H-hat quantum programming language Python interpreter"
dynamic = ["version"]
authors = [
    { name = "Eduardo Maschio", email = "eduardo.maschio@hhat-lang.org" }
]
readme = "README"
requires-python = ">=3.12"
license = { text = "MIT" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development",
    "Topic :: Software Development :: Interpreters",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [

]

[project.optional-dependencies]
heather_base = [
    "arpeggio",
]
# to insert the relevant libraries for each low level language and backend
heather_qiskit = [
    "hhat-lang[heather_base]",
    "qiskit",
]
heather_squidasm = [
    "hhat-lang[heather_base]",
    "netqasm",
    "squidasm"
]
heather_cqasm = [

]

dev = [
    "mypy",
    "pytest",
    "pytest-xdist",
    "pytest-mypy",
    "ipython",
    "black",
    "isort",
    "pre-commit",
]

[tool.setuptools_scm]
root = ".."
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"

[project.urls]
Home = "https://github.com/hhat-lang/hhat_lang"
Issues = "https://github.com/hhat-lang/hhat_lang/issues"
Documentation = "https://docs.hhat-lang.org"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
select = ["E", "F", "I", "Q"]
extend-ignore = ["F841", "F403", "F401"]
line-length = 100

[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "E402", "I002"]

[tool.mypy]
python_version = "3.12"
