name: Python CI

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./python
          pip install pytest
      - name: Run tests
        run: pytest
